"""Translate only AtlasBrain-owned messages; never translate interpolated project content."""
from contextlib import contextmanager
from contextvars import ContextVar

_LANGUAGE = ContextVar("atlasbrain_language", default="pt-BR")
MESSAGES = {
    "Já existia nota sobre isso: atualizei `": "A note already existed: updated `",
    "` com o que era novo:\n": "` with new information:\n",
    "Nenhuma nota encontrada para '": "No note found for '",
    "'. Use `buscar` para localizar.": "'. Use search to locate it.",
    "Nada encontrado para: ": "No results for: ",
    " resultado(s) para “": " result(s) for “",
    "” · ler todos ≈ ": "” · read all ≈ ",
    "   Motivos: ": "   Reasons: ",
    "Seção “": "Section “",
    "” não encontrada em `": "” not found in `",
    "`. Disponíveis: ": "`. Available: ",
    "\n\n[… cortado em ": "\n\n[… truncated at ",
    " de ": " of ",
    " caracteres": " characters",
    ". Peça uma parte com `secao`: ": ". Request a section with section: ",
    " · modificado ": " · modified ",
    "**Revisão:** ": "**Revision:** ",
    "**Aponta para:** ": "**Links to:** ",
    "**Usado/citado por:** ": "**Used/referenced by:** ",
    "## Vizinhança de ": "## Neighbors of ",
    "Aponta para": "Links to",
    "Citada por / usada por": "Referenced/used by",
    "\n**Parecidas pelo conteúdo (inferido):**\n": "\n**Similar content (inferred):**\n",
    " (similaridade ": " (similarity ",
    "\n**Mesmas tags:**\n": "\n**Shared tags:**\n",
    " tag(s) em comum)": " shared tag(s))",
    "\n**Links para notas que ainda não existem:** ": "\n**Pending note links:** ",
    "\nNota isolada: sem links, backlinks, tags ou semelhantes.": "\nIsolated note: no links, backlinks, tags or semantic neighbors.",
    "Não há caminho entre `": "No path between `",
    "` e `": "` and `",
    "` na direção ": "` in direction ",
    "Caminho com ": "Path with ",
    " salto(s) · direção ": " hop(s) · direction ",
    " · evidência L": " · evidence L",
    "# Mapa do segundo cérebro": "# Second-brain map",
    "**Arquivos:** ": "**Files:** ",
    " · **ligações:** ": " · **links:** ",
    "\n## Hubs (notas mais conectadas)": "\n## Hubs (most connected notes)",
    " conexões)": " connections)",
    "\n## Agrupamentos de assuntos": "\n## Topic communities",
    "- **Grupo ": "- **Group ",
    " notas): ": " notes): ",
    "\n**Notas órfãs (sem nenhuma conexão):** ": "\n**Isolated notes (no connections):** ",
    ": índice ausente": ": index missing",
    ": índice indisponível (": ": index unavailable (",
    "Sem links, backlinks, similaridade, tags ou wikilinks pendentes no índice completo; não significa arquivo sem uso.": "No links, backlinks, similarity, tags or pending wikilinks in the full index; does not prove a file is unused.",
    "Nenhuma tag ainda.": "No tags yet.",
    "Nenhuma nota com #": "No note with #",
    "Pasta inválida: precisa ficar dentro do segundo cérebro.": "Invalid folder: must be inside the project brain.",
    "Nota criada: `": "Note created: `",
    "Consulta vazia.": "Empty query.",
    "Nenhum arquivo com “": "No file with “",
    "” no nome ou nos símbolos. Tente `buscar` (conteúdo e significado).": "” in its name or symbols. Try search (content and meaning).",
    " — define ": " — defines ",
    "Nenhum símbolo “": "No symbol “",
    "” no índice. Tente `arquivos` ou `buscar`.": "” in the index. Try find_files or search.",
    "**Definição de `": "**Definition of `",
    "**Definições de `": "**Definitions of `",
    "  Usado em (": "  Used in (",
    " dentro de `": " inside `",
    " usos adicionais; use `consultar_grafo`.": " additional usages; use query_graph.",
    "  Nenhum uso resolvido no índice; isso não comprova código morto.": "  No resolved usage in the index; this does not prove dead code.",
    "Há definições homônimas. Use o ID para consultar uma delas; referências sem destino único permanecem ambíguas.": "Multiple definitions share this name. Use the ID to select one; references without a unique target remain ambiguous.",
    " referência(s) ambígua(s) ficaram sem ligação:": " ambiguous reference(s) have no link:",
    "Não achei arquivo nem símbolo “": "No file or symbol found for “",
    "”. Tente `arquivos` ou `buscar`.": "”. Try find_files or search.",
    "\n**Define (": "\n**Defines (",
    "Importa": "Imports",
    "Chama": "Calls",
    "Importado por": "Imported by",
    "Chamado por": "Called by",
    "Citado em notas/decisões": "Referenced in notes/decisions",
    "Cita": "References",
    "\n**Porquê / notas no código:**": "\n**Rationale / code notes:**",
    "\n**Parecidos pelo conteúdo (INFERRED):** ": "\n**Similar content (INFERRED):** ",
    " (substituiu `": " (superseded `",
    "\nAtenção: ": "\nNotice: ",
    "Decisão registrada: `": "Decision recorded: `",
    "Aprendizado registrado: `": "Learning recorded: `",
    "Atualizei `": "Updated `",
    "` com:\n": "` with:\n",
    "Nenhuma decisão registrada ainda.": "No decisions recorded yet.",
    "sem projeto": "no project",
    "Mesmo título, decisões ativas com números diferentes. Revise o conteúdo antes de substituir.": "Same title, active decisions with different numbers. Review their content before superseding.",
    "Informe o grupo preparado para enviar um resumo.": "Supply the prepared group when submitting a summary.",
    "Índice ocupado ou indisponível; tente novamente após a indexação.": "Index busy or unavailable; retry after indexing.",
    "profundidade deve estar entre 0 e 6.": "depth must be between 0 and 6.",
    "tokens deve estar entre 128 e 16000.": "tokens must be between 128 and 16000.",
    "direcao deve ser entrada, saida ou ambas.": "direction must be incoming, outgoing or both.",
    "modo deve ser bfs ou dfs.": "mode must be bfs or dfs.",
    "Relações válidas: ": "Valid relations: ",
    "[TRUNCADO: limite de contexto atingido; reduza a consulta ou aumente tokens/profundidade.]": "[TRUNCATED: context limit reached; narrow the query or increase tokens/depth.]",
    "Não achei `": "Could not find `",
    "` no grafo. Use `arquivos`, `onde` ou `buscar`.": "` in the graph. Use find_files, symbol_location or search.",
    "` é ambíguo; informe o caminho ou ID:\n": "` is ambiguous; specify a path or ID:\n",
    " opções adicionais.": " additional options.",
    "Nenhum resultado para `": "No results for `",
    "Grafo: ": "Graph: ",
    " · até ": " · up to ",
    " salto(s) ": " hop(s) ",
    " salto(s).": " hop(s).",
    " salto(s): ": " hop(s): ",
    " · direção ": " · direction ",
    "Setas seguem a relação original. INFERRED é hipótese. Tokens estimados por UTF-8/4.": "Arrows follow the original relation. INFERRED is a hypothesis. Tokens estimated using UTF-8/4.",
    "NÓ ": "NODE ",
    " referência(s) ambígua(s) nesses arquivos ficaram sem aresta:": " ambiguous reference(s) in these files have no edge:",
    "Impacto potencial de ": "Potential impact of ",
    "Dependências estáticas; não é garantia de quebra nem de cobertura completa.": "Static dependencies do not guarantee breakage or complete coverage.",
    "INFERRED incluídas.": "INFERRED included.",
    "Somente relações EXTRACTED; INFERRED ficam de fora.": "EXTRACTED relations only; INFERRED excluded.",
    "Nenhum dependente encontrado dentro desses limites.": "No dependents found within these limits.",
    " referência(s) ambígua(s) podem ocultar dependentes:": " ambiguous reference(s) may hide dependents:",
    " (misto)": " (mixed)",
    "# atlasbrain — relatório\n\nAinda não há arquivos indexados.\n": "# atlasbrain — report\n\nNo indexed files yet.\n",
    "# atlasbrain — relatório de ": "# atlasbrain — report for ",
    "_Gerado em ": "_Generated at ",
    ". Arquivo local, recriado a cada indexação._": ". Local file, rebuilt with each indexing pass._",
    " arquivos · ": " files · ",
    " arquivos": " files",
    " símbolos · ": " symbols · ",
    " ligações entre arquivos** (": " file-to-file links** (",
    "). Procedência: ": "). Provenance: ",
    " extraídas do código/texto, ": " extracted from code/text, ",
    " inferidas, ": " inferred, ",
    " ambíguas.": " ambiguous.",
    "**Grafo de símbolos:** ": "**Symbol graph:** ",
    " chamadas/heranças resolvidas (": " resolved calls/inheritance (",
    " chamadas no mesmo arquivo); ": " same-file calls); ",
    " referências ambíguas sem aresta.": " ambiguous references without an edge.",
    "_Direção e relações paralelas são preservadas nas consultas; comunidades e interface usam a projeção por arquivos._": "_Direction and parallel relations are preserved in queries; communities and the interface use the file projection._",
    "## God nodes — por onde tudo passa": "## Hubs — highly connected files",
    " conexões (": " connections (",
    "## Subsistemas (comunidades)": "## Subsystems (communities)",
    "## Conexões surpreendentes": "## Surprising connections",
    "_Ligações entre partes distantes do projeto (outra pasta e outro subsistema)._": "_Links between distant project areas (different folders and subsystems)._",
    "- nenhuma por enquanto": "- none yet",
    "## O porquê no código": "## Rationale in code",
    "_Comentários NOTE / WHY / HACK / DECISION extraídos da AST._": "_NOTE / WHY / HACK / DECISION comments extracted from the AST._",
    "- nenhum encontrado": "- none found",
    "- …e ": "- …and ",
    " TODO/FIXME espalhados (use `explicar` num arquivo para ver os dele)": " TODO/FIXME comments (use explain on a file to inspect them)",
    "## Decisões ligadas ao código": "## Decisions linked to code",
    "## Perguntas que o grafo responde bem": "## Questions the graph can answer",
    "Como `": "How does `",
    "` se conecta a `": "` connect to `",
    "`? → `caminho`": "`? → graph_path",
    "O que depende de `": "What depends on `",
    "` e o que quebra se eu mudar? → `explicar`": "` and what could break if it changes? → explain",
    "Por que `": "Why is `",
    "` está ligado a `": "` linked to `",
    "`? → `explicar`": "`? → explain",
    "Quais decisões afetam `": "Which decisions affect `",
    "`? → `decisoes` + `explicar`": "`? → decisions + explain",
    "Onde está definido `<símbolo>` e quem usa? → `onde`": "Where is <symbol> defined and used? → symbol_location",
    "Compara tamanho e data dos arquivos indexáveis com o índice; não reindexa nem prova ausência de mudanças com metadados idênticos.": "Compares indexable file sizes and dates with the index; does not reindex or rule out changes with identical metadata.",
    "Nomes semelhantes": "Similar names",
    "Arquivos na mesma pasta": "Files in the same folder",
    "Proximidade de nomes/pastas não prova dependência. Revise ambos antes de registrar.": "Similar names or folders do not prove dependency. Review both files before recording a link.",
    "Escolha dois arquivos distintos e um motivo de até 2000 caracteres": "Choose two distinct files and a reason of up to 2000 characters",
    "Arquivo não encontrado no índice": "File not found in the index",
    "Orçamento insuficiente; aumente tokens ou use uma ferramenta específica.": "Insufficient budget; increase tokens or use a more specific tool.",
    "Descreva a tarefa": "Describe the task",
    "Objetivo inválido": "Invalid objective",
    "foco explícito": "explicit focus",
    "relevância de busca": "search relevance",
    "checkbox explícito": "explicit checkbox",
    "Foco não encontrado: ": "Focus not found: ",
    "Foco em decisão histórica: ": "Focus on historical decision: ",
    " arquivos pendentes de indexação": " files pending indexing",
    "Indexação em andamento; o contexto pode mudar": "Indexing in progress; context may change",
    "Há relações inferidas; confirme no código antes de alterar": "Inferred relations exist; check the code before changing it",
    "Síntese desatualizada: ": "Stale summary: ",
    "Contexto selecionado por relevância de busca; não é uma análise exaustiva. Use impacto/explicar para aprofundar.": "Context selected by search relevance; not an exhaustive analysis. Use impact/explain for details.",
    "Arquivo maior que 200 KB": "File larger than 200 KB",
    "Arquivo maior que o limite do editor (200 KB)": "File exceeds the editor limit (200 KB)",
    "Arquivo não encontrado": "File not found",
    "Arquivos ocultos e pastas geradas não podem ser editados": "Hidden files and generated folders cannot be edited",
    "Caminho fora do projeto": "Path outside the project",
    "Caminho inválido": "Invalid path",
    "Conteúdo inválido": "Invalid content",
    "Conteúdo maior que 200 KB": "Content exceeds 200 KB",
    "Histórico inválido": "Invalid history",
    "Identificador de operação inválido": "Invalid operation identifier",
    "Identificador já usado para outra operação": "Identifier already used for another operation",
    "Já existe um arquivo com esse nome": "A file with this name already exists",
    "Já existe um arquivo com esse nome. Escolha outro.": "A file with this name already exists. Choose another.",
    "Links simbólicos não podem ser editados": "Symbolic links cannot be edited",
    "Nome da seção inválido": "Invalid section name",
    "O arquivo foi removido ou não existe mais": "The file was removed or no longer exists",
    "O arquivo mudou durante o salvamento. Recarregue antes de salvar.": "The file changed while saving. Reload before saving.",
    "O arquivo mudou fora do editor. Recarregue a versão atual antes de salvar.": "The file changed outside the editor. Reload the current version before saving.",
    "O editor aceita apenas Markdown": "The editor only accepts Markdown",
    "O editor aceita arquivos UTF-8": "The editor only accepts UTF-8 files",
    "O editor aceita conteúdo UTF-8 válido": "The editor only accepts valid UTF-8 content",
    "O relatório é gerado automaticamente": "The report is generated automatically",
    "Operação interrompida: confira o arquivo antes de tentar com outro identificador": "Operation interrupted: inspect the file before trying another identifier",
    "Pasta de recuperação inválida": "Invalid recovery folder",
    "Pasta do cérebro inválida": "Invalid brain folder",
    "Pastas internas não podem ser editadas": "Internal folders cannot be edited",
    "Seção repetida: use a edição completa para desambiguar": "Repeated section: use the full editor to disambiguate",
    "Use um caminho relativo dentro do projeto": "Use a relative path within the project",
    "Versão anterior indisponível": "Previous version unavailable",
    "Versão inválida": "Invalid version",
    "Versão não encontrada": "Version not found",
    "Revisar se o arquivo faz parte de um fluxo do projeto e documentar seus vínculos; ausência de conexões no índice não prova código sem uso.": "Review whether the file belongs to a project flow and document its links; no indexed connections does not prove unused code.",
    "Adicionar uma tag de assunto ou um link para uma nota relacionada, após revisar o conteúdo.": "Add a topic tag or a link to a related note after reviewing its content."
}

def text(message):
    return MESSAGES.get(message, message) if _LANGUAGE.get() == "en" else message

@contextmanager
def language(locale):
    token = _LANGUAGE.set(locale)
    try:
        yield
    finally:
        _LANGUAGE.reset(token)

def is_english():
    return _LANGUAGE.get() == "en"


def value(item):
    if not is_english():
        return item
    from .mcp_api import RESULT_VALUES
    return RESULT_VALUES.get(item, item)
